### ISSUE TITLE
Missing instance/object for parameter route for Zend\Mvc\Router...

### ISSUE THREAD

**Issue by rgilchrist** [vasrap/ZF2-Restful-Module-Skeleton#13]
Hi
I have just installed the ZF2 Skeleton Application and cloned your module to module/Main, and added 'Main' to config/application.config.php

But when I go to the URL's 
http://<my domain>/
http://<my domain>/info.json

I get the error below.

Can you tell me how to fix this?

Thanks
Rob

Fatal error: Uncaught exception 'Zend\Di\Exception\MissingPropertyException' with message 'Missing instance/object for parameter route for Zend\Mvc\Router\Http\Literal::__construct' in /www/Zend/vendor/zendframework/zendframework/library/Zend/Di/Di.php:699 Stack trace: #0 /www/Zend/vendor/zendframework/zendframework/library/Zend/Di/Di.php(393): Zend\Di\Di->resolveMethodParameters('Zend\Mvc\Router...', '__construct', Array, NULL, true, true) #1 /www/Zend/vendor/zendframework/zendframework/library/Zend/Di/Di.php(225): Zend\Di\Di->createInstanceViaConstructor('Zend\Mvc\Router...', Array, NULL) #2 /www/Zend/vendor/zendframework/zendframework/library/Zend/Di/Di.php(174): Zend\Di\Di->newInstance('Zend\Mvc\Router...', Array, true) #3 /www/Zend/vendor/zendframework/zendframework/library/Zend/ServiceManager/Di/DiServiceFactory.php(104): Zend\Di\Di->get('Zend\Mvc\Router...', Array) #4 /www/Zend/vendor/zendframework/zendframework/library/Zend/ServiceManager/Di/DiAbstractServiceFactory.php(43): Zend\ServiceManager\Di\DiServiceFactory in /www/Zend/vendor/zendframework/zendframework/library/Zend/ServiceManager/ServiceManager.php on line 749

**Comment by rgilchrist** [comment]
Hi
The problem was in version ZF2.1 (https://github.com/zendframework/zf2/issues/3625)

I got it working by removing the 'Zend\Mvc\Router\Http\' in 

Application/config/module.config.php:14
Main/configs/module.config.php:26

It works as expected now.

Cheers
Rob
