### ISSUE TITLE
Service with name "json-pp" could not be created.

### ISSUE THREAD

**Issue by nilamrsharma** [vasrap/ZF2-Restful-Module-Skeleton#20]
Hi ,

We are upgrading laminas 3 from laminas 2 and we are getting below error,

`[Thu Jun 16 00:45:33.497009 2022] [php:notice] [pid 29] [client 172.17.0.1:41805] Exception: Service with name "json-pp" could not be created. Reason: Could not resolve value for parameter "vars" of type any in class Shipwire\\ApiClient\\PostProcessor\\Json (requested as json-pp) --- Backtrace: #0 /var/www/shipwire.www/swclient/vendor/laminas/laminas-servicemanager/src/ServiceManager.php(234): Laminas\\ServiceManager\\ServiceManager->doCreate()\n#1 /var/www/shipwire.www/swclient/module/Main/Module.php(793): Laminas\\ServiceManager\\ServiceManager->get()\n#2 /var/www/shipwire.www/swclient/vendor/laminas/laminas-eventmanager/src/EventManager.php(319): Main\\Module->errorProcess()\n#3 /var/www/shipwire.www/swclient/vendor/laminas/laminas-eventmanager/src/EventManager.php(171): Laminas\\EventManager\\EventManager->triggerListeners()\n#4 /var/www/shipwire.www/swclient/vendor/laminas/laminas-mvc/src/DispatchListener.php(146): Laminas\\EventManager\\EventManager->triggerEvent()\n#5 /var/www/shipwire.www/swclient/vendor/laminas/laminas-eventmanager/src/EventManager.php(319): Laminas\\Mvc\\DispatchListener->onDispatch()\n#6 /var/www/shipwire.www/swclient/vendor/laminas/laminas-eventmanager/src/EventManager.php(179): Laminas\\EventManager\\EventManager->triggerListeners()\n#7 /var/www/shipwire.www/swclient/vendor/laminas/laminas-mvc/src/Application.php(325): Laminas\\EventManager\\EventManager->triggerEventUntil()\n#8 /var/ww
`

**Comment by vasrap** [comment]
Ah. Good luck!
